if(EXISTS "/home/nico/WORK_ROOT/RAZOR_repo/build_tests/compression_test[1]_tests.cmake")
  include("/home/nico/WORK_ROOT/RAZOR_repo/build_tests/compression_test[1]_tests.cmake")
else()
  add_test(compression_test_NOT_BUILT compression_test_NOT_BUILT)
endif()
