add_test([=[NaryTreeTest.Initialization]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/nary_tree_test [==[--gtest_filter=NaryTreeTest.Initialization]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NaryTreeTest.Initialization]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NaryTreeTest.RootNodeExists]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/nary_tree_test [==[--gtest_filter=NaryTreeTest.RootNodeExists]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NaryTreeTest.RootNodeExists]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NaryTreeTest.InsertSingleChild]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/nary_tree_test [==[--gtest_filter=NaryTreeTest.InsertSingleChild]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NaryTreeTest.InsertSingleChild]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NaryTreeTest.InsertMultipleChildren]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/nary_tree_test [==[--gtest_filter=NaryTreeTest.InsertMultipleChildren]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NaryTreeTest.InsertMultipleChildren]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NaryTreeTest.FindChild]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/nary_tree_test [==[--gtest_filter=NaryTreeTest.FindChild]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NaryTreeTest.FindChild]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NaryTreeTest.FindNonExistentChild]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/nary_tree_test [==[--gtest_filter=NaryTreeTest.FindNonExistentChild]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NaryTreeTest.FindNonExistentChild]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NaryTreeTest.DeleteChild]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/nary_tree_test [==[--gtest_filter=NaryTreeTest.DeleteChild]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NaryTreeTest.DeleteChild]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NaryTreeTest.DeleteNonEmptyDirectory]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/nary_tree_test [==[--gtest_filter=NaryTreeTest.DeleteNonEmptyDirectory]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NaryTreeTest.DeleteNonEmptyDirectory]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NaryTreeTest.DeleteEmptyDirectory]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/nary_tree_test [==[--gtest_filter=NaryTreeTest.DeleteEmptyDirectory]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NaryTreeTest.DeleteEmptyDirectory]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NaryTreeTest.CreateNestedPath]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/nary_tree_test [==[--gtest_filter=NaryTreeTest.CreateNestedPath]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NaryTreeTest.CreateNestedPath]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NaryTreeTest.LockRead]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/nary_tree_test [==[--gtest_filter=NaryTreeTest.LockRead]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NaryTreeTest.LockRead]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NaryTreeTest.LockWrite]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/nary_tree_test [==[--gtest_filter=NaryTreeTest.LockWrite]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NaryTreeTest.LockWrite]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NaryTreeTest.InvalidLockIndex]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/nary_tree_test [==[--gtest_filter=NaryTreeTest.InvalidLockIndex]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NaryTreeTest.InvalidLockIndex]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NaryTreeTest.ConcurrentReads]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/nary_tree_test [==[--gtest_filter=NaryTreeTest.ConcurrentReads]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NaryTreeTest.ConcurrentReads]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NaryTreeTest.ConcurrentInserts]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/nary_tree_test [==[--gtest_filter=NaryTreeTest.DISABLED_ConcurrentInserts]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NaryTreeTest.ConcurrentInserts]=]  PROPERTIES DISABLED TRUE)
set_tests_properties([=[NaryTreeTest.ConcurrentInserts]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NaryTreeTest.ConcurrentMixedOperations]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/nary_tree_test [==[--gtest_filter=NaryTreeTest.ConcurrentMixedOperations]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NaryTreeTest.ConcurrentMixedOperations]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NaryTreeTest.InvalidParameters]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/nary_tree_test [==[--gtest_filter=NaryTreeTest.InvalidParameters]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NaryTreeTest.InvalidParameters]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NaryTreeTest.CapacityLimit]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/nary_tree_test [==[--gtest_filter=NaryTreeTest.CapacityLimit]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NaryTreeTest.CapacityLimit]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NaryTreeTest.DeepNesting]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/nary_tree_test [==[--gtest_filter=NaryTreeTest.DeepNesting]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NaryTreeTest.DeepNesting]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NaryTreeTest.ManyChildren]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/nary_tree_test [==[--gtest_filter=NaryTreeTest.ManyChildren]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NaryTreeTest.ManyChildren]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  nary_tree_test_TESTS NaryTreeTest.Initialization NaryTreeTest.RootNodeExists NaryTreeTest.InsertSingleChild NaryTreeTest.InsertMultipleChildren NaryTreeTest.FindChild NaryTreeTest.FindNonExistentChild NaryTreeTest.DeleteChild NaryTreeTest.DeleteNonEmptyDirectory NaryTreeTest.DeleteEmptyDirectory NaryTreeTest.CreateNestedPath NaryTreeTest.LockRead NaryTreeTest.LockWrite NaryTreeTest.InvalidLockIndex NaryTreeTest.ConcurrentReads NaryTreeTest.ConcurrentInserts NaryTreeTest.ConcurrentMixedOperations NaryTreeTest.InvalidParameters NaryTreeTest.CapacityLimit NaryTreeTest.DeepNesting NaryTreeTest.ManyChildren)
