if(EXISTS "/home/nico/WORK_ROOT/RAZOR_repo/build_tests/shm_persist_test[1]_tests.cmake")
  include("/home/nico/WORK_ROOT/RAZOR_repo/build_tests/shm_persist_test[1]_tests.cmake")
else()
  add_test(shm_persist_test_NOT_BUILT shm_persist_test_NOT_BUILT)
endif()
