add_test([=[ShmPersistTest.CreateNewTree]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/shm_persist_test [==[--gtest_filter=ShmPersistTest.CreateNewTree]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShmPersistTest.CreateNewTree]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShmPersistTest.CreateAndDetach]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/shm_persist_test [==[--gtest_filter=ShmPersistTest.CreateAndDetach]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShmPersistTest.CreateAndDetach]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShmPersistTest.CreateDetachReattach]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/shm_persist_test [==[--gtest_filter=ShmPersistTest.CreateDetachReattach]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShmPersistTest.CreateDetachReattach]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShmPersistTest.StringTablePersistence]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/shm_persist_test [==[--gtest_filter=ShmPersistTest.StringTablePersistence]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShmPersistTest.StringTablePersistence]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShmPersistTest.DirectoryHierarchyPersistence]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/shm_persist_test [==[--gtest_filter=ShmPersistTest.DirectoryHierarchyPersistence]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShmPersistTest.DirectoryHierarchyPersistence]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShmPersistTest.FileMetadataPersistence]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/shm_persist_test [==[--gtest_filter=ShmPersistTest.FileMetadataPersistence]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShmPersistTest.FileMetadataPersistence]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShmPersistTest.Cleanup]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/shm_persist_test [==[--gtest_filter=ShmPersistTest.Cleanup]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShmPersistTest.Cleanup]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShmPersistTest.InvalidDetach]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/shm_persist_test [==[--gtest_filter=ShmPersistTest.InvalidDetach]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShmPersistTest.InvalidDetach]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShmPersistTest.DoubleDetach]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/shm_persist_test [==[--gtest_filter=ShmPersistTest.DISABLED_DoubleDetach]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShmPersistTest.DoubleDetach]=]  PROPERTIES DISABLED TRUE)
set_tests_properties([=[ShmPersistTest.DoubleDetach]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShmPersistTest.ManyFilesAcrossRemounts]=]  /home/nico/WORK_ROOT/RAZOR_repo/build_tests/shm_persist_test [==[--gtest_filter=ShmPersistTest.DISABLED_ManyFilesAcrossRemounts]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShmPersistTest.ManyFilesAcrossRemounts]=]  PROPERTIES DISABLED TRUE)
set_tests_properties([=[ShmPersistTest.ManyFilesAcrossRemounts]=]  PROPERTIES WORKING_DIRECTORY /home/nico/WORK_ROOT/RAZOR_repo/build_tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  shm_persist_test_TESTS ShmPersistTest.CreateNewTree ShmPersistTest.CreateAndDetach ShmPersistTest.CreateDetachReattach ShmPersistTest.StringTablePersistence ShmPersistTest.DirectoryHierarchyPersistence ShmPersistTest.FileMetadataPersistence ShmPersistTest.Cleanup ShmPersistTest.InvalidDetach ShmPersistTest.DoubleDetach ShmPersistTest.ManyFilesAcrossRemounts)
